<?php
/**
 * ProjectRBI – Master Configuration
 * Generated by setup wizard on 1779345406.
 */

// ── Prevent browser caching during development ────────────────────────────────
header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
header('Pragma: no-cache');
header('Expires: Thu, 01 Jan 1970 00:00:00 GMT');

// ── Barangay Identity ─────────────────────────────────────────────────────────
define('BRGY_NUMBER',   '410');
define('BRGY_NAME',     'Barangay 410');
define('BRGY_ZONE',     'Zone 42');
define('BRGY_FULLNAME', 'Barangay 410 Zone 42');
define('BRGY_CITY',     'City of Manila');
define('BRGY_DISTRICT', 'IV');
define('BRGY_PROVINCE', 'Metro Manila');

// ── E-Blotter ─────────────────────────────────────────────────────────────────
define('BLOTTER_CASE_PREFIX',   'BRGY 410');
define('BLOTTER_DEFAULT_SIGNER','JUAN');

// ── Database ──────────────────────────────────────────────────────────────────
define('DB_HOST', 'localhost');
define('DB_PORT', 3306);
define('DB_USER', 'root');
define('DB_PASS', '');
define('DB_NAME', 'projectrbi');

// ── App Appearance ────────────────────────────────────────────────────────────
define('APP_THEME_COLOR', '#0f172a');

// ── Derived ───────────────────────────────────────────────────────────────────
define('BRGY_FULL_ADDRESS', BRGY_NAME . ', ' . BRGY_CITY . ', ' . BRGY_PROVINCE);