<?php
/**
 * ProjectRBI – Master Configuration
 * Generated by setup wizard on 1781142897.
 */

// ── Block direct browser access ───────────────────────────────────────────────
if (basename($_SERVER['SCRIPT_FILENAME'] ?? '') === 'config.php') {
    http_response_code(403); exit('Access denied.');
}

// ── Barangay Identity ─────────────────────────────────────────────────────────
define('BRGY_NUMBER',   '410');
define('BRGY_NAME',     'Barangay 410');
define('BRGY_ZONE',     '42');
define('BRGY_FULLNAME', 'Barangay 410 42');
define('BRGY_CITY',     'City of Manila');
define('BRGY_DISTRICT', '4th');
define('BRGY_PROVINCE', 'Metro Manila');

// ── Map Coordinates ───────────────────────────────────────────────────────────
define('BRGY_LAT', 14.5995);
define('BRGY_LNG', 120.9842);

// ── E-Blotter ─────────────────────────────────────────────────────────────────
define('BLOTTER_CASE_PREFIX',   'BRGY 410');
define('BLOTTER_DEFAULT_SIGNER','Marvin Santiago');

// ── Database ──────────────────────────────────────────────────────────────────
define('DB_HOST', 'localhost');
define('DB_PORT', 3306);
define('DB_USER', 'root');
define('DB_PASS', '');
define('DB_NAME', 'projectrbi');

// ── App Appearance ────────────────────────────────────────────────────────────
define('APP_THEME_COLOR', '#ffb6c1');

// ── Derived ───────────────────────────────────────────────────────────────────
define('BRGY_FULL_ADDRESS', BRGY_NAME . ', ' . BRGY_CITY . ', ' . BRGY_PROVINCE);