<?php
/**
 * ProjectRBI – Setup Wizard
 * Run once after installing. Writes config.php and seeds the database.
 * Access: http://localhost/ProjectRBI/ProjectRBI/install.php
 */

// ─── Lockout after setup is done ────────────────────────────────────────────
// Uncomment the next 3 lines once setup is complete to prevent re-running:
// if (file_exists(__DIR__.'/install.lock')) {
//     die('<h2>Setup already completed. Delete install.lock to re-run.</h2>');
// }

session_start();

$step    = (int)($_GET['step'] ?? 1);
$errors  = [];
$success = '';

// ─── Step 3: Write config + test DB ─────────────────────────────────────────
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['action'])) {

    if ($_POST['action'] === 'save_brgy') {
        $_SESSION['setup']['brgy_number']   = trim($_POST['brgy_number']   ?? '');
        $_SESSION['setup']['brgy_name']     = trim($_POST['brgy_name']     ?? '');
        $_SESSION['setup']['brgy_city']     = trim($_POST['brgy_city']     ?? '');
        $_SESSION['setup']['brgy_district'] = trim($_POST['brgy_district'] ?? '');
        $_SESSION['setup']['brgy_province'] = trim($_POST['brgy_province'] ?? '');
        $_SESSION['setup']['signer_name']   = strtoupper(trim($_POST['signer_name'] ?? ''));
        header('Location: install.php?step=2');
        exit();
    }

    if ($_POST['action'] === 'save_db') {
        $db_host = trim($_POST['db_host'] ?? 'localhost');
        $db_user = trim($_POST['db_user'] ?? 'root');
        $db_pass = trim($_POST['db_pass'] ?? '');
        $db_name = trim($_POST['db_name'] ?? 'projectrbi');

        // Test connection (port 3307 = bundled MariaDB)
        $test = @new mysqli($db_host, $db_user, $db_pass, '', 3307);
        if ($test->connect_error) {
            $errors[] = "Database connection failed: " . htmlspecialchars($test->connect_error);
        } else {
            $_SESSION['setup']['db_host'] = $db_host;
            $_SESSION['setup']['db_user'] = $db_user;
            $_SESSION['setup']['db_pass'] = $db_pass;
            $_SESSION['setup']['db_name'] = $db_name;
            header('Location: install.php?step=3');
            exit();
        }
    }

    if ($_POST['action'] === 'save_admin') {
        $admin_user  = trim($_POST['admin_user']  ?? '');
        $admin_pass  = trim($_POST['admin_pass']  ?? '');
        $admin_pass2 = trim($_POST['admin_pass2'] ?? '');
        $admin_name  = trim($_POST['admin_name']  ?? '');

        if (empty($admin_user))             $errors[] = "Username is required.";
        if (strlen($admin_pass) < 6)        $errors[] = "Password must be at least 6 characters.";
        if ($admin_pass !== $admin_pass2)   $errors[] = "Passwords do not match.";

        if (empty($errors)) {
            $s = $_SESSION['setup'];

            // Build config file content
            $brgy_number  = addslashes($s['brgy_number']   ?? '410');
            $brgy_name    = addslashes($s['brgy_name']     ?? 'Barangay 410');
            $brgy_city    = addslashes($s['brgy_city']     ?? 'Manila');
            $brgy_district= addslashes($s['brgy_district'] ?? '1st District');
            $brgy_province= addslashes($s['brgy_province'] ?? 'Metro Manila');
            $signer_name  = addslashes($s['signer_name']   ?? '');
            $db_host      = addslashes($s['db_host']       ?? 'localhost');
            $db_user_c    = addslashes($s['db_user']       ?? 'root');
            $db_pass_c    = addslashes($s['db_pass']       ?? '');
            $db_name_c    = addslashes($s['db_name']       ?? 'projectrbi');

            $config_content = <<<PHP
<?php
/**
 * ProjectRBI – Master Configuration
 * Generated by setup wizard on {$_SERVER['REQUEST_TIME']}.
 */

// ── Barangay Identity ─────────────────────────────────────────────────────────
define('BRGY_NUMBER',   '$brgy_number');
define('BRGY_NAME',     '$brgy_name');
define('BRGY_CITY',     '$brgy_city');
define('BRGY_DISTRICT', '$brgy_district');
define('BRGY_PROVINCE', '$brgy_province');

// ── E-Blotter ─────────────────────────────────────────────────────────────────
define('BLOTTER_CASE_PREFIX',   'BRGY $brgy_number');
define('BLOTTER_DEFAULT_SIGNER','$signer_name');

// ── Database ──────────────────────────────────────────────────────────────────
define('DB_HOST', '$db_host');
define('DB_PORT', 3307);
define('DB_USER', '$db_user_c');
define('DB_PASS', '$db_pass_c');
define('DB_NAME', '$db_name_c');

// ── App Appearance ────────────────────────────────────────────────────────────
define('APP_THEME_COLOR', '#0f172a');

// ── Derived ───────────────────────────────────────────────────────────────────
define('BRGY_FULL_ADDRESS', BRGY_NAME . ', ' . BRGY_CITY . ', ' . BRGY_PROVINCE);
PHP;

            // Write config.php
            $config_path = __DIR__ . '/config.php';
            if (file_put_contents($config_path, $config_content) === false) {
                $errors[] = "Could not write config.php — check folder permissions.";
            } else {
                // Connect and create DB + admin account
                $conn = new mysqli(
                    $s['db_host'] ?? 'localhost',
                    $s['db_user'] ?? 'root',
                    $s['db_pass'] ?? '',
                    '',
                    3307
                );
                if ($conn->connect_error) {
                    $errors[] = "DB connection failed: " . htmlspecialchars($conn->connect_error);
                } else {
                    $conn->query("CREATE DATABASE IF NOT EXISTS `" . $conn->real_escape_string($s['db_name']) . "` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
                    $conn->select_db($s['db_name']);

                    // Create admins table if it doesn't exist
                    $conn->query("CREATE TABLE IF NOT EXISTS admins (
                        id INT AUTO_INCREMENT PRIMARY KEY,
                        username VARCHAR(100) NOT NULL UNIQUE,
                        password VARCHAR(255) NOT NULL,
                        full_name VARCHAR(150) DEFAULT NULL,
                        role ENUM('captain','secretary','guest') NOT NULL DEFAULT 'secretary',
                        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
                    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");

                    $hashed = password_hash($admin_pass, PASSWORD_DEFAULT);
                    $stmt = $conn->prepare("INSERT INTO admins (username, password, full_name, role) VALUES (?, ?, ?, 'captain') ON DUPLICATE KEY UPDATE password=?, full_name=?");
                    $stmt->bind_param('sssss', $admin_user, $hashed, $admin_name, $hashed, $admin_name);
                    $stmt->execute();
                    $stmt->close();
                    $conn->close();

                    // Create lock file
                    file_put_contents(__DIR__ . '/install.lock', date('Y-m-d H:i:s'));

                    header('Location: install.php?step=4');
                    exit();
                }
            }
        }
        $step = 3;
    }
}

// ─── Redirect to step 2 if step 1 not filled ────────────────────────────────
if ($step === 2 && empty($_SESSION['setup']['brgy_number'])) {
    header('Location: install.php?step=1'); exit();
}
if ($step === 3 && empty($_SESSION['setup']['db_host'])) {
    header('Location: install.php?step=2'); exit();
}

$s = $_SESSION['setup'] ?? [];
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>ProjectRBI Setup Wizard</title>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Syne:wght@700;800&display=swap" rel="stylesheet"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"/>
<style>
*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
body{font-family:'Inter',sans-serif;background:linear-gradient(135deg,#0f172a 0%,#1e3a5f 100%);min-height:100vh;display:flex;align-items:center;justify-content:center;padding:2rem}
.wizard{background:#fff;border-radius:20px;box-shadow:0 20px 60px rgba(0,0,0,.35);max-width:600px;width:100%;overflow:hidden}
.wizard-head{background:linear-gradient(135deg,#0f172a,#1e3a5f);padding:2rem 2rem 1.5rem;text-align:center}
.wizard-logo{font-family:'Syne',sans-serif;font-size:1.8rem;font-weight:800;color:#fff;margin-bottom:.25rem}
.wizard-sub{font-size:.8rem;color:rgba(255,255,255,.5);letter-spacing:.1em;text-transform:uppercase}
.steps{display:flex;justify-content:center;gap:0;padding:1.25rem 2rem 0}
.step-dot{display:flex;flex-direction:column;align-items:center;gap:4px;flex:1;position:relative}
.step-dot::before{content:'';position:absolute;top:14px;left:calc(50% + 14px);right:calc(-50% + 14px);height:2px;background:rgba(255,255,255,.2)}
.step-dot:last-child::before{display:none}
.dot{width:28px;height:28px;border-radius:50%;border:2px solid rgba(255,255,255,.3);color:rgba(255,255,255,.4);font-size:12px;font-weight:700;display:flex;align-items:center;justify-content:center;transition:.2s}
.step-dot.done .dot{background:#22c55e;border-color:#22c55e;color:#fff}
.step-dot.active .dot{background:#3b82f6;border-color:#3b82f6;color:#fff}
.dot-label{font-size:10px;color:rgba(255,255,255,.4);font-weight:500;white-space:nowrap}
.step-dot.active .dot-label,.step-dot.done .dot-label{color:rgba(255,255,255,.8)}
.wizard-body{padding:2rem}
h2{font-family:'Syne',sans-serif;font-size:1.2rem;font-weight:800;color:#0f172a;margin-bottom:.25rem}
.desc{font-size:.8rem;color:#64748b;margin-bottom:1.5rem}
.form-row{display:grid;grid-template-columns:1fr 1fr;gap:1rem}
.form-group{display:flex;flex-direction:column;gap:6px;margin-bottom:1rem}
label{font-size:.78rem;font-weight:600;color:#374151}
input,select{padding:10px 12px;border:1.5px solid #e2e8f0;border-radius:9px;font-size:.85rem;font-family:inherit;color:#0f172a;transition:.15s;outline:none}
input:focus,select:focus{border-color:#3b82f6;box-shadow:0 0 0 3px rgba(59,130,246,.12)}
.hint{font-size:.72rem;color:#94a3b8}
.btn{display:inline-flex;align-items:center;gap:8px;padding:11px 22px;border-radius:10px;font-size:.875rem;font-weight:600;cursor:pointer;border:none;transition:.15s}
.btn-primary{background:#3b82f6;color:#fff}
.btn-primary:hover{background:#2563eb}
.btn-secondary{background:#f1f5f9;color:#374151}
.btn-secondary:hover{background:#e2e8f0}
.form-actions{display:flex;justify-content:flex-end;gap:.75rem;margin-top:.5rem}
.alert{padding:10px 14px;border-radius:9px;font-size:.82rem;margin-bottom:1.25rem}
.alert-error{background:#fff1f2;border:1px solid #fecdd3;color:#be123c}
.alert-success{background:#f0fdf4;border:1px solid #bbf7d0;color:#15803d}
.done-icon{width:80px;height:80px;background:linear-gradient(135deg,#22c55e,#16a34a);border-radius:50%;display:flex;align-items:center;justify-content:center;margin:0 auto 1.5rem;font-size:2.2rem;color:#fff}
.done-links{display:flex;flex-direction:column;gap:.75rem;margin-top:1.5rem}
.done-link{display:flex;align-items:center;gap:10px;padding:12px 16px;background:#f8fafc;border-radius:10px;text-decoration:none;color:#0f172a;font-size:.85rem;font-weight:500;border:1px solid #e2e8f0;transition:.15s}
.done-link:hover{background:#eff6ff;border-color:#bfdbfe}
.done-link i{color:#3b82f6;width:18px;text-align:center}
</style>
</head>
<body>
<div class="wizard">
  <div class="wizard-head">
    <div class="wizard-logo">ProjectRBI</div>
    <div class="wizard-sub">Barangay Records Management System &bull; Setup Wizard</div>
    <div class="steps">
      <div class="step-dot <?= $step>=1?($step>1?'done':'active'):'' ?>">
        <div class="dot"><?= $step>1?'<i class="fas fa-check"></i>':'1' ?></div>
        <div class="dot-label">Barangay</div>
      </div>
      <div class="step-dot <?= $step>=2?($step>2?'done':'active'):'' ?>">
        <div class="dot"><?= $step>2?'<i class="fas fa-check"></i>':'2' ?></div>
        <div class="dot-label">Database</div>
      </div>
      <div class="step-dot <?= $step>=3?($step>3?'done':'active'):'' ?>">
        <div class="dot"><?= $step>3?'<i class="fas fa-check"></i>':'3' ?></div>
        <div class="dot-label">Admin</div>
      </div>
      <div class="step-dot <?= $step>=4?'active':'' ?>">
        <div class="dot"><?= $step>=4?'<i class="fas fa-check"></i>':'4' ?></div>
        <div class="dot-label">Done</div>
      </div>
    </div>
  </div>

  <div class="wizard-body">
  <?php if (!empty($errors)): ?>
    <div class="alert alert-error"><i class="fas fa-circle-exclamation"></i> <?= implode('<br>', $errors) ?></div>
  <?php endif; ?>

  <?php if ($step === 1): ?>
    <h2>Barangay Information</h2>
    <p class="desc">Enter your barangay details. These will appear on all documents and reports.</p>
    <form method="post">
      <input type="hidden" name="action" value="save_brgy"/>
      <div class="form-row">
        <div class="form-group">
          <label>Barangay Number</label>
          <input name="brgy_number" required placeholder="e.g. 410" value="<?= htmlspecialchars($s['brgy_number'] ?? '') ?>"/>
        </div>
        <div class="form-group">
          <label>Barangay Name</label>
          <input name="brgy_name" required placeholder="e.g. Barangay 410" value="<?= htmlspecialchars($s['brgy_name'] ?? '') ?>"/>
        </div>
      </div>
      <div class="form-row">
        <div class="form-group">
          <label>City / Municipality</label>
          <input name="brgy_city" required placeholder="e.g. Manila" value="<?= htmlspecialchars($s['brgy_city'] ?? '') ?>"/>
        </div>
        <div class="form-group">
          <label>District</label>
          <input name="brgy_district" placeholder="e.g. 1st District" value="<?= htmlspecialchars($s['brgy_district'] ?? '') ?>"/>
        </div>
      </div>
      <div class="form-group">
        <label>Province / Region</label>
        <input name="brgy_province" placeholder="e.g. Metro Manila" value="<?= htmlspecialchars($s['brgy_province'] ?? '') ?>"/>
      </div>
      <div class="form-group">
        <label>Punong Barangay Full Name <span style="color:#94a3b8;font-weight:400">(used as default document signer)</span></label>
        <input name="signer_name" style="text-transform:uppercase" placeholder="e.g. JUAN DELA CRUZ" value="<?= htmlspecialchars($s['signer_name'] ?? '') ?>"/>
        <span class="hint">Will be uppercased automatically on blotter documents.</span>
      </div>
      <div class="form-actions">
        <button class="btn btn-primary" type="submit">Next <i class="fas fa-arrow-right"></i></button>
      </div>
    </form>

  <?php elseif ($step === 2): ?>
    <h2>Database Connection</h2>
    <p class="desc">Enter the MySQL / MariaDB credentials. For XAMPP, the defaults below usually work.</p>
    <form method="post">
      <input type="hidden" name="action" value="save_db"/>
      <div class="form-row">
        <div class="form-group">
          <label>Host</label>
          <input name="db_host" value="<?= htmlspecialchars($s['db_host'] ?? 'localhost') ?>"/>
        </div>
        <div class="form-group">
          <label>Database Name</label>
          <input name="db_name" value="<?= htmlspecialchars($s['db_name'] ?? 'projectrbi') ?>"/>
          <span class="hint">Created automatically if it doesn't exist.</span>
        </div>
      </div>
      <div class="form-row">
        <div class="form-group">
          <label>Username</label>
          <input name="db_user" value="<?= htmlspecialchars($s['db_user'] ?? 'root') ?>"/>
        </div>
        <div class="form-group">
          <label>Password</label>
          <input name="db_pass" type="password" placeholder="(blank for XAMPP default)" value="<?= htmlspecialchars($s['db_pass'] ?? '') ?>"/>
        </div>
      </div>
      <div class="form-actions">
        <a href="install.php?step=1" class="btn btn-secondary"><i class="fas fa-arrow-left"></i> Back</a>
        <button class="btn btn-primary" type="submit">Test &amp; Continue <i class="fas fa-arrow-right"></i></button>
      </div>
    </form>

  <?php elseif ($step === 3): ?>
    <h2>Admin Account</h2>
    <p class="desc">Create the first captain account. This account has full access to all modules.</p>
    <form method="post">
      <input type="hidden" name="action" value="save_admin"/>
      <div class="form-group">
        <label>Full Name</label>
        <input name="admin_name" required placeholder="e.g. Juan Dela Cruz"/>
      </div>
      <div class="form-group">
        <label>Username</label>
        <input name="admin_user" required placeholder="e.g. admin"/>
      </div>
      <div class="form-row">
        <div class="form-group">
          <label>Password</label>
          <input name="admin_pass" type="password" required placeholder="Min. 6 characters"/>
        </div>
        <div class="form-group">
          <label>Confirm Password</label>
          <input name="admin_pass2" type="password" required placeholder="Repeat password"/>
        </div>
      </div>
      <div class="form-actions">
        <a href="install.php?step=2" class="btn btn-secondary"><i class="fas fa-arrow-left"></i> Back</a>
        <button class="btn btn-primary" type="submit"><i class="fas fa-check"></i> Finish Setup</button>
      </div>
    </form>

  <?php elseif ($step === 4): ?>
    <div style="text-align:center">
      <div class="done-icon"><i class="fas fa-check"></i></div>
      <h2 style="text-align:center;margin-bottom:.5rem">Setup Complete!</h2>
      <p class="desc" style="text-align:center">Your ProjectRBI system is ready. Open the links below to get started.</p>
    </div>
    <div class="done-links">
      <a href="Home.php" class="done-link"><i class="fas fa-house"></i> Go to Dashboard</a>
      <a href="admin.php" class="done-link"><i class="fas fa-right-to-bracket"></i> Login Page</a>
      <a href="config.php" class="done-link" target="_blank"><i class="fas fa-gear"></i> View config.php (verify settings)</a>
    </div>
    <p style="font-size:.75rem;color:#94a3b8;text-align:center;margin-top:1.25rem">
      <i class="fas fa-lock"></i> For security, the setup wizard is now locked.<br>
      Delete <code>install.lock</code> only if you need to re-run setup.
    </p>
  <?php endif; ?>
  </div>
</div>
</body>
</html>
