<?php
/**
 * ProjectRBI — Web Installer
 * Place this file in your project root and visit it in the browser.
 * After setup is complete, DELETE this file for security.
 */

session_start();
define('INSTALLER_VERSION', '1.0.0');

// ── Block if already installed ────────────────────────────────────────────────
if (file_exists(__DIR__ . '/config.php') && !isset($_GET['force'])) {
    $cfg = file_get_contents(__DIR__ . '/config.php');
    if (strpos($cfg, 'Generated by setup wizard') !== false) {
        // Already installed — show warning
        $already_installed = true;
    }
}

// ── Step management ───────────────────────────────────────────────────────────
$step = (int)($_POST['step'] ?? $_GET['step'] ?? 1);
$errors   = [];
$success  = [];

// ── Helper: write config.php ──────────────────────────────────────────────────
function writeConfig(array $d): bool {
    $blotter_signer = addslashes($d['signer_name'] ?? '');
    $ts = time();
    $content = <<<PHP
<?php
/**
 * ProjectRBI – Master Configuration
 * Generated by setup wizard on {$ts}.
 */

// ── Block direct browser access ───────────────────────────────────────────────
if (basename(\$_SERVER['SCRIPT_FILENAME'] ?? '') === 'config.php') {
    http_response_code(403); exit('Access denied.');
}

// ── Barangay Identity ─────────────────────────────────────────────────────────
define('BRGY_NUMBER',   '{$d['brgy_number']}');
define('BRGY_NAME',     '{$d['brgy_name']}');
define('BRGY_ZONE',     '{$d['brgy_zone']}');
define('BRGY_FULLNAME', '{$d['brgy_name']} {$d['brgy_zone']}');
define('BRGY_CITY',     '{$d['brgy_city']}');
define('BRGY_DISTRICT', '{$d['brgy_district']}');
define('BRGY_PROVINCE', '{$d['brgy_province']}');

// ── Map Coordinates ───────────────────────────────────────────────────────────
define('BRGY_LAT', {$d['brgy_lat']});
define('BRGY_LNG', {$d['brgy_lng']});

// ── E-Blotter ─────────────────────────────────────────────────────────────────
define('BLOTTER_CASE_PREFIX',   'BRGY {$d['brgy_number']}');
define('BLOTTER_DEFAULT_SIGNER','{$blotter_signer}');

// ── Database ──────────────────────────────────────────────────────────────────
define('DB_HOST', '{$d['db_host']}');
define('DB_PORT', {$d['db_port']});
define('DB_USER', '{$d['db_user']}');
define('DB_PASS', '{$d['db_pass']}');
define('DB_NAME', '{$d['db_name']}');

// ── App Appearance ────────────────────────────────────────────────────────────
define('APP_THEME_COLOR', '{$d['theme_color']}');

// ── Derived ───────────────────────────────────────────────────────────────────
define('BRGY_FULL_ADDRESS', BRGY_NAME . ', ' . BRGY_CITY . ', ' . BRGY_PROVINCE);
PHP;
    return file_put_contents(__DIR__ . '/config.php', $content) !== false;
}

// ── Helper: test DB connection ────────────────────────────────────────────────
function testDb(string $host, int $port, string $user, string $pass, string $name = ''): array {
    $conn = @new mysqli($host, $user, $pass, '', $port);
    if ($conn->connect_error) return ['ok' => false, 'msg' => $conn->connect_error];
    if ($name) {
        if (!$conn->select_db($name)) {
            // Try to create it
            if (!$conn->query("CREATE DATABASE IF NOT EXISTS `$name` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci"))
                return ['ok' => false, 'msg' => 'Cannot create database: ' . $conn->error];
        }
    }
    return ['ok' => true, 'conn' => $conn];
}

// ── STEP PROCESSING ───────────────────────────────────────────────────────────

// Save step data to session
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $step = (int)($_POST['step'] ?? 1);

    // ── Step 1: Barangay Info ──
    if ($step === 1) {
        $_SESSION['setup']['brgy_number']   = trim($_POST['brgy_number']   ?? '');
        $_SESSION['setup']['brgy_name']     = trim($_POST['brgy_name']     ?? '');
        $_SESSION['setup']['brgy_zone']     = trim($_POST['brgy_zone']     ?? '');
        $_SESSION['setup']['brgy_city']     = trim($_POST['brgy_city']     ?? '');
        $_SESSION['setup']['brgy_district'] = trim($_POST['brgy_district'] ?? '');
        $_SESSION['setup']['brgy_province'] = trim($_POST['brgy_province'] ?? 'Metro Manila');
        $_SESSION['setup']['brgy_lat']      = trim($_POST['brgy_lat']      ?? '14.5995');
        $_SESSION['setup']['brgy_lng']      = trim($_POST['brgy_lng']      ?? '120.9842');
        $_SESSION['setup']['signer_name']   = trim($_POST['signer_name']   ?? '');
        $_SESSION['setup']['theme_color']   = trim($_POST['theme_color']   ?? '#0f172a');

        if (!$_SESSION['setup']['brgy_number'] || !$_SESSION['setup']['brgy_name'] || !$_SESSION['setup']['brgy_city'])
            $errors[] = 'Barangay number, name, and city are required.';
        else $step = 2;
    }

    // ── Step 2: Database ──
    elseif ($step === 2) {
        $_SESSION['setup']['db_host'] = trim($_POST['db_host'] ?? 'localhost');
        $_SESSION['setup']['db_port'] = (int)($_POST['db_port'] ?? 3306);
        $_SESSION['setup']['db_user'] = trim($_POST['db_user'] ?? 'root');
        $_SESSION['setup']['db_pass'] = $_POST['db_pass'] ?? '';
        $_SESSION['setup']['db_name'] = trim($_POST['db_name'] ?? 'projectrbi');

        $test = testDb(
            $_SESSION['setup']['db_host'],
            $_SESSION['setup']['db_port'],
            $_SESSION['setup']['db_user'],
            $_SESSION['setup']['db_pass'],
            $_SESSION['setup']['db_name']
        );
        if (!$test['ok']) $errors[] = 'Database connection failed: ' . $test['msg'];
        else $step = 3;
    }

    // ── Step 3: Admin Account ──
    elseif ($step === 3) {
        $admin_name  = trim($_POST['admin_name']  ?? '');
        $admin_user  = trim($_POST['admin_user']  ?? '');
        $admin_pass  = $_POST['admin_pass']  ?? '';
        $admin_pass2 = $_POST['admin_pass2'] ?? '';
        $admin_role  = $_POST['admin_role']  ?? 'captain';

        if (!$admin_name || !$admin_user || !$admin_pass)
            $errors[] = 'All admin fields are required.';
        elseif (strlen($admin_pass) < 8)
            $errors[] = 'Password must be at least 8 characters.';
        elseif ($admin_pass !== $admin_pass2)
            $errors[] = 'Passwords do not match.';
        else {
            $_SESSION['setup']['admin_name'] = $admin_name;
            $_SESSION['setup']['admin_user'] = $admin_user;
            $_SESSION['setup']['admin_pass'] = password_hash($admin_pass, PASSWORD_DEFAULT);
            $_SESSION['setup']['admin_role'] = $admin_role;
            $step = 4;
        }
    }

    // ── Step 4: Install ──
    elseif ($step === 4) {
        $d    = $_SESSION['setup'] ?? [];
        $log  = [];
        $fail = false;

        // 1. Write config.php
        if (writeConfig($d)) {
            $log[] = ['ok' => true,  'msg' => 'config.php written successfully'];
        } else {
            $log[] = ['ok' => false, 'msg' => 'Failed to write config.php — check folder permissions'];
            $fail  = true;
        }

        // 2. Connect to DB
        $db = testDb($d['db_host'], $d['db_port'], $d['db_user'], $d['db_pass'], $d['db_name']);
        if (!$db['ok']) {
            $log[] = ['ok' => false, 'msg' => 'Database connection failed: ' . $db['msg']];
            $fail  = true;
        } else {
            $conn = $db['conn'];
            $log[] = ['ok' => true, 'msg' => 'Connected to database: ' . $d['db_name']];

            // 3. Create admins table
            $conn->query("CREATE TABLE IF NOT EXISTS admins (
                id          INT AUTO_INCREMENT PRIMARY KEY,
                username    VARCHAR(100) NOT NULL UNIQUE,
                password    VARCHAR(255) NOT NULL,
                full_name   VARCHAR(150) NOT NULL,
                role        ENUM('captain','secretary') NOT NULL DEFAULT 'secretary',
                is_active   TINYINT(1) DEFAULT 1,
                created_at  DATETIME DEFAULT CURRENT_TIMESTAMP
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
            $log[] = ['ok' => true, 'msg' => 'admins table ready'];

            // 4. Insert admin account
            $uname  = $conn->real_escape_string($d['admin_user']);
            $pwhash = $conn->real_escape_string($d['admin_pass']);
            $fname  = $conn->real_escape_string($d['admin_name']);
            $role   = $conn->real_escape_string($d['admin_role']);

            // Check if username already exists
            $chk = $conn->query("SELECT id FROM admins WHERE username='$uname' LIMIT 1");
            if ($chk && $chk->num_rows > 0) {
                $conn->query("UPDATE admins SET password='$pwhash', full_name='$fname', role='$role', is_active=1 WHERE username='$uname'");
                $log[] = ['ok' => true, 'msg' => "Admin account '$uname' updated (already existed)"];
            } else {
                $conn->query("INSERT INTO admins (username, password, full_name, role) VALUES ('$uname','$pwhash','$fname','$role')");
                $log[] = ['ok' => true, 'msg' => "Admin account '$uname' created successfully"];
            }

            // 5. Create residents table (core table)
            $conn->query("CREATE TABLE IF NOT EXISTS residents (
                id             INT AUTO_INCREMENT PRIMARY KEY,
                resident_code  VARCHAR(25)  DEFAULT NULL,
                family_code    VARCHAR(25)  DEFAULT NULL,
                last_name      VARCHAR(100) NOT NULL,
                first_name     VARCHAR(100) NOT NULL,
                middle_name    VARCHAR(100) DEFAULT NULL,
                suffix         VARCHAR(20)  DEFAULT NULL,
                gender         VARCHAR(20)  DEFAULT NULL,
                birthdate      DATE         DEFAULT NULL,
                civil_status   VARCHAR(30)  DEFAULT NULL,
                religion       VARCHAR(60)  DEFAULT NULL,
                nationality    VARCHAR(60)  DEFAULT 'Filipino',
                address        VARCHAR(255) DEFAULT NULL,
                contact_number VARCHAR(20)  DEFAULT NULL,
                email          VARCHAR(120) DEFAULT NULL,
                voter          VARCHAR(10)  DEFAULT NULL,
                employment     VARCHAR(50)  DEFAULT NULL,
                occupation     VARCHAR(100) DEFAULT NULL,
                education      VARCHAR(60)  DEFAULT NULL,
                is_pwd         TINYINT(1)   DEFAULT 0,
                is_solo_parent TINYINT(1)   DEFAULT 0,
                is_hidden      TINYINT(1)   DEFAULT 0,
                lat            DECIMAL(10,7) DEFAULT NULL,
                lng            DECIMAL(10,7) DEFAULT NULL,
                created_at     DATETIME     DEFAULT CURRENT_TIMESTAMP,
                updated_at     DATETIME     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
            $log[] = ['ok' => true, 'msg' => 'residents table ready'];

            // 6. Create blotter_cases table
            $conn->query("CREATE TABLE IF NOT EXISTS blotter_cases (
                id                  INT AUTO_INCREMENT PRIMARY KEY,
                case_id             VARCHAR(50)  NOT NULL UNIQUE,
                complainant_first   VARCHAR(100) NOT NULL,
                complainant_middle  VARCHAR(100) DEFAULT NULL,
                complainant_last    VARCHAR(100) NOT NULL,
                complainant_age     INT          DEFAULT NULL,
                complainant_address VARCHAR(255) DEFAULT NULL,
                respondent_first    VARCHAR(100) NOT NULL,
                respondent_middle   VARCHAR(100) DEFAULT NULL,
                respondent_last     VARCHAR(100) NOT NULL,
                respondent_address  VARCHAR(255) DEFAULT NULL,
                when_incident       DATE         DEFAULT NULL,
                where_incident      VARCHAR(255) DEFAULT NULL,
                brief_case          TEXT         DEFAULT NULL,
                disposition         VARCHAR(50)  DEFAULT NULL,
                status              VARCHAR(50)  DEFAULT 'Pending',
                created_by          VARCHAR(150) DEFAULT NULL,
                summons_done        TINYINT(1)   DEFAULT 0,
                notice_done         TINYINT(1)   DEFAULT 0,
                mediation_done      TINYINT(1)   DEFAULT 0,
                hearing_date        DATE         DEFAULT NULL,
                mediation_outcome   VARCHAR(100) DEFAULT NULL,
                mediation_reason    TEXT         DEFAULT NULL,
                last_updated_by     VARCHAR(150) DEFAULT NULL,
                last_updated_at     DATETIME     DEFAULT NULL,
                last_exported_by    VARCHAR(150) DEFAULT NULL,
                last_exported_at    DATETIME     DEFAULT NULL,
                created_at          DATETIME     DEFAULT CURRENT_TIMESTAMP,
                updated_at          DATETIME     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
            $log[] = ['ok' => true, 'msg' => 'blotter_cases table ready'];

            // 7. Create certificate_requests table
            $conn->query("CREATE TABLE IF NOT EXISTS certificate_templates (
                id            INT AUTO_INCREMENT PRIMARY KEY,
                template_name VARCHAR(150) NOT NULL,
                template_body TEXT         DEFAULT NULL,
                is_active     TINYINT(1)   DEFAULT 1,
                created_at    DATETIME     DEFAULT CURRENT_TIMESTAMP
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
            $conn->query("CREATE TABLE IF NOT EXISTS certificate_requests (
                id           INT AUTO_INCREMENT PRIMARY KEY,
                resident_id  INT          DEFAULT NULL,
                template_id  INT          DEFAULT NULL,
                purpose      VARCHAR(255) DEFAULT NULL,
                status       VARCHAR(50)  DEFAULT 'Pending',
                requested_by VARCHAR(150) DEFAULT NULL,
                requested_at DATETIME     DEFAULT CURRENT_TIMESTAMP,
                updated_at   DATETIME     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
            $log[] = ['ok' => true, 'msg' => 'certificate tables ready'];

            // 8. Create document_requests table
            $conn->query("CREATE TABLE IF NOT EXISTS document_requests (
                id             INT AUTO_INCREMENT PRIMARY KEY,
                request_code   VARCHAR(50)  DEFAULT NULL,
                resident_name  VARCHAR(200) DEFAULT NULL,
                document_type  VARCHAR(100) DEFAULT NULL,
                status         VARCHAR(50)  DEFAULT 'Pending',
                requested_at   DATETIME     DEFAULT CURRENT_TIMESTAMP,
                updated_at     DATETIME     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
            $log[] = ['ok' => true, 'msg' => 'document_requests table ready'];

            // 9. Create audit_log table
            $conn->query("CREATE TABLE IF NOT EXISTS audit_log (
                id           INT AUTO_INCREMENT PRIMARY KEY,
                action       VARCHAR(100) NOT NULL,
                table_name   VARCHAR(100) DEFAULT NULL,
                record_id    INT          DEFAULT NULL,
                performed_by VARCHAR(150) DEFAULT NULL,
                performed_at DATETIME     DEFAULT CURRENT_TIMESTAMP,
                details      TEXT         DEFAULT NULL
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
            $log[] = ['ok' => true, 'msg' => 'audit_log table ready'];

            // 10. Create eb_signer_settings
            $signer = $conn->real_escape_string($d['signer_name'] ?? '');
            $conn->query("CREATE TABLE IF NOT EXISTS eb_signer_settings (
                id          INT NOT NULL DEFAULT 1,
                signer_name VARCHAR(200) NOT NULL DEFAULT '$signer',
                updated_at  DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                PRIMARY KEY (id)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
            if ($signer) {
                $conn->query("INSERT IGNORE INTO eb_signer_settings (id, signer_name) VALUES (1, '$signer')");
            }
            $log[] = ['ok' => true, 'msg' => 'eb_signer_settings table ready'];

            // 11. Seed default certificate templates
            $conn->query("INSERT IGNORE INTO certificate_templates (id, template_name) VALUES
                (1, 'Barangay Clearance'),
                (2, 'Certificate of Residency'),
                (3, 'Certificate of Indigency'),
                (4, 'Barangay Business Clearance'),
                (5, 'Certificate of Good Moral Character')
            ");
            $log[] = ['ok' => true, 'msg' => 'Default certificate templates seeded'];
        }

        $_SESSION['install_log']  = $log;
        $_SESSION['install_fail'] = $fail;
        $_SESSION['setup_done']   = !$fail;
        $step = 5;
    }
}

$setup = $_SESSION['setup'] ?? [];
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width,initial-scale=1"/>
  <title>ProjectRBI — Setup Installer</title>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Syne:wght@700;800&display=swap" rel="stylesheet"/>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"/>
  <style>
    *,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
    body{font-family:'Inter',sans-serif;background:#060d1a;min-height:100vh;display:flex;flex-direction:column;align-items:center;padding:2rem 1rem;}

    .installer-wrap{width:100%;max-width:680px;}

    /* Header */
    .installer-header{text-align:center;margin-bottom:2rem;}
    .installer-header .logo{width:56px;height:56px;background:linear-gradient(135deg,#3b82f6,#1d4ed8);border-radius:16px;display:flex;align-items:center;justify-content:center;margin:0 auto 1rem;font-size:24px;color:#fff;}
    .installer-header h1{font-family:'Syne',sans-serif;font-size:1.6rem;font-weight:800;color:#fff;margin-bottom:.25rem;}
    .installer-header p{color:rgba(255,255,255,.4);font-size:.85rem;}

    /* Progress steps */
    .progress-bar{display:flex;align-items:center;margin-bottom:2rem;gap:0;}
    .prog-step{display:flex;align-items:center;flex:1;}
    .prog-dot{width:32px;height:32px;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:.75rem;font-weight:700;flex-shrink:0;transition:all .3s;}
    .prog-dot.done{background:#22c55e;color:#fff;}
    .prog-dot.active{background:#3b82f6;color:#fff;box-shadow:0 0 0 4px rgba(59,130,246,.25);}
    .prog-dot.pending{background:rgba(255,255,255,.08);color:rgba(255,255,255,.3);border:1.5px solid rgba(255,255,255,.1);}
    .prog-label{font-size:10px;color:rgba(255,255,255,.4);margin-top:4px;text-align:center;white-space:nowrap;}
    .prog-step-inner{display:flex;flex-direction:column;align-items:center;}
    .prog-line{flex:1;height:2px;background:rgba(255,255,255,.08);margin:0 4px;margin-bottom:16px;}
    .prog-line.done{background:#22c55e;}

    /* Card */
    .card{background:#0d1526;border:1px solid rgba(255,255,255,.08);border-radius:16px;padding:2rem;margin-bottom:1rem;}
    .card-title{font-family:'Syne',sans-serif;font-size:1.15rem;font-weight:800;color:#fff;margin-bottom:.35rem;display:flex;align-items:center;gap:.6rem;}
    .card-title i{font-size:1.1rem;color:#3b82f6;}
    .card-sub{font-size:.82rem;color:rgba(255,255,255,.35);margin-bottom:1.5rem;}

    /* Form fields */
    .field{margin-bottom:1.1rem;}
    .field label{display:block;font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:.07em;color:rgba(255,255,255,.4);margin-bottom:.4rem;}
    .field input,.field select{width:100%;background:rgba(255,255,255,.05);border:1px solid rgba(255,255,255,.1);border-radius:9px;padding:10px 14px;color:#fff;font-size:13px;font-family:'Inter',sans-serif;outline:none;transition:border .2s;}
    .field input:focus,.field select:focus{border-color:rgba(59,130,246,.6);box-shadow:0 0 0 3px rgba(59,130,246,.12);}
    .field input::placeholder{color:rgba(255,255,255,.2);}
    .field select option{background:#0d1526;color:#fff;}
    .field-row{display:grid;grid-template-columns:1fr 1fr;gap:.75rem;}
    .field-row-3{display:grid;grid-template-columns:1fr 1fr 1fr;gap:.75rem;}
    .field-hint{font-size:11px;color:rgba(255,255,255,.25);margin-top:.3rem;}

    /* Buttons */
    .btn-row{display:flex;gap:.75rem;margin-top:1.5rem;justify-content:flex-end;}
    .btn{display:inline-flex;align-items:center;gap:.5rem;padding:10px 20px;border-radius:9px;font-family:'Inter',sans-serif;font-size:13px;font-weight:600;cursor:pointer;border:none;transition:all .2s;text-decoration:none;}
    .btn-primary{background:linear-gradient(135deg,#3b82f6,#2563eb);color:#fff;}
    .btn-primary:hover{transform:translateY(-1px);box-shadow:0 6px 20px rgba(59,130,246,.35);}
    .btn-ghost{background:rgba(255,255,255,.06);color:rgba(255,255,255,.7);border:1px solid rgba(255,255,255,.1);}
    .btn-ghost:hover{background:rgba(255,255,255,.1);}
    .btn-success{background:linear-gradient(135deg,#22c55e,#16a34a);color:#fff;}
    .btn-danger{background:linear-gradient(135deg,#ef4444,#dc2626);color:#fff;}

    /* Alerts */
    .alert{padding:.85rem 1rem;border-radius:9px;font-size:.84rem;margin-bottom:1rem;display:flex;align-items:flex-start;gap:.6rem;}
    .alert-error{background:rgba(239,68,68,.1);border:1px solid rgba(239,68,68,.25);color:#fca5a5;}
    .alert-warning{background:rgba(245,158,11,.1);border:1px solid rgba(245,158,11,.25);color:#fbbf24;}
    .alert-info{background:rgba(59,130,246,.1);border:1px solid rgba(59,130,246,.25);color:#93c5fd;}
    .alert-success{background:rgba(34,197,94,.1);border:1px solid rgba(34,197,94,.25);color:#86efac;}

    /* Log items */
    .log-item{display:flex;align-items:center;gap:.75rem;padding:.6rem .75rem;border-radius:8px;margin-bottom:.4rem;font-size:.83rem;}
    .log-item.ok{background:rgba(34,197,94,.08);color:#86efac;}
    .log-item.fail{background:rgba(239,68,68,.08);color:#fca5a5;}
    .log-item i{font-size:.9rem;flex-shrink:0;}

    /* Already installed warning */
    .installed-banner{background:rgba(245,158,11,.1);border:1.5px solid rgba(245,158,11,.3);border-radius:12px;padding:1.25rem;color:#fbbf24;margin-bottom:1.5rem;font-size:.85rem;}
    .installed-banner strong{display:block;font-size:1rem;margin-bottom:.25rem;}

    /* Footer */
    .installer-footer{text-align:center;font-size:11px;color:rgba(255,255,255,.2);margin-top:1.5rem;}

    /* Password strength */
    .pw-strength{height:4px;border-radius:99px;margin-top:.4rem;transition:all .3s;background:rgba(255,255,255,.1);}
    .pw-strength.weak{background:#ef4444;width:33%;}
    .pw-strength.medium{background:#f59e0b;width:66%;}
    .pw-strength.strong{background:#22c55e;width:100%;}
  </style>
</head>
<body>

<div class="installer-wrap">

  <!-- Header -->
  <div class="installer-header">
    <div class="logo"><i class="fas fa-shield-halved"></i></div>
    <h1>ProjectRBI Installer</h1>
    <p>Barangay Records & Blotter Information System &mdash; v<?= INSTALLER_VERSION ?></p>
  </div>

  <!-- Already installed warning -->
  <?php if (!empty($already_installed) && $step < 4): ?>
  <div class="installed-banner">
    <strong><i class="fas fa-triangle-exclamation"></i> System already installed</strong>
    A <code>config.php</code> already exists. Running setup again will overwrite it.
    <a href="setup.php?force=1" style="color:#fbbf24;font-weight:700"> Continue anyway &rarr;</a>
  </div>
  <?php endif; ?>

  <!-- Progress bar -->
  <?php
  $steps = ['Barangay','Database','Admin','Install','Done'];
  $totalSteps = count($steps);
  ?>
  <div class="progress-bar">
    <?php foreach ($steps as $i => $label):
      $n = $i + 1;
      $cls = $n < $step ? 'done' : ($n === $step ? 'active' : 'pending');
      $icon = $n < $step ? '<i class="fas fa-check"></i>' : $n;
    ?>
      <div class="prog-step">
        <div class="prog-step-inner">
          <div class="prog-dot <?= $cls ?>"><?= $n < $step ? '<i class="fas fa-check"></i>' : $n ?></div>
          <div class="prog-label"><?= $label ?></div>
        </div>
        <?php if ($i < $totalSteps - 1): ?>
        <div class="prog-line <?= $n < $step ? 'done' : '' ?>"></div>
        <?php endif; ?>
      </div>
    <?php endforeach; ?>
  </div>

  <!-- Error display -->
  <?php if ($errors): ?>
  <div class="alert alert-error">
    <i class="fas fa-exclamation-circle" style="flex-shrink:0;margin-top:2px"></i>
    <div><?= implode('<br>', array_map('htmlspecialchars', $errors)) ?></div>
  </div>
  <?php endif; ?>

  <!-- ── STEP 1: Barangay Info ── -->
  <?php if ($step === 1): ?>
  <div class="card">
    <div class="card-title"><i class="fas fa-building"></i> Barangay Information</div>
    <div class="card-sub">Enter your barangay's details. These will appear on documents and certificates.</div>
    <form method="POST">
      <input type="hidden" name="step" value="1">
      <div class="field-row">
        <div class="field">
          <label>Barangay Number *</label>
          <input type="text" name="brgy_number" value="<?= htmlspecialchars($setup['brgy_number'] ?? '') ?>" placeholder="e.g. 410" required>
        </div>
        <div class="field">
          <label>Zone / Purok</label>
          <input type="text" name="brgy_zone" value="<?= htmlspecialchars($setup['brgy_zone'] ?? '') ?>" placeholder="e.g. Zone 42">
        </div>
      </div>
      <div class="field">
        <label>Barangay Name *</label>
        <input type="text" name="brgy_name" value="<?= htmlspecialchars($setup['brgy_name'] ?? '') ?>" placeholder="e.g. Barangay 410" required>
      </div>
      <div class="field-row">
        <div class="field">
          <label>City / Municipality *</label>
          <input type="text" name="brgy_city" value="<?= htmlspecialchars($setup['brgy_city'] ?? 'City of Manila') ?>" placeholder="e.g. City of Manila" required>
        </div>
        <div class="field">
          <label>District</label>
          <input type="text" name="brgy_district" value="<?= htmlspecialchars($setup['brgy_district'] ?? '') ?>" placeholder="e.g. IV">
        </div>
      </div>
      <div class="field">
        <label>Province / Region</label>
        <input type="text" name="brgy_province" value="<?= htmlspecialchars($setup['brgy_province'] ?? 'Metro Manila') ?>" placeholder="e.g. Metro Manila">
      </div>
      <div class="field-row">
        <div class="field">
          <label>Latitude</label>
          <input type="text" name="brgy_lat" value="<?= htmlspecialchars($setup['brgy_lat'] ?? '14.5995') ?>" placeholder="14.5995">
          <div class="field-hint">For map features (optional)</div>
        </div>
        <div class="field">
          <label>Longitude</label>
          <input type="text" name="brgy_lng" value="<?= htmlspecialchars($setup['brgy_lng'] ?? '120.9842') ?>" placeholder="120.9842">
        </div>
      </div>
      <div class="field">
        <label>Default Document Signer (Punong Barangay)</label>
        <input type="text" name="signer_name" value="<?= htmlspecialchars($setup['signer_name'] ?? '') ?>" placeholder="e.g. JUAN DELA CRUZ">
        <div class="field-hint">Name that appears on PDFs — can be changed later in Signer Settings</div>
      </div>
      <div class="field">
        <label>Theme Color</label>
        <input type="color" name="theme_color" value="<?= htmlspecialchars($setup['theme_color'] ?? '#0f172a') ?>" style="height:40px;padding:4px 8px;cursor:pointer">
      </div>
      <div class="btn-row">
        <button type="submit" class="btn btn-primary">Next &rarr; Database Setup</button>
      </div>
    </form>
  </div>

  <!-- ── STEP 2: Database ── -->
  <?php elseif ($step === 2): ?>
  <div class="card">
    <div class="card-title"><i class="fas fa-database"></i> Database Configuration</div>
    <div class="card-sub">Enter your MySQL database credentials. The database will be created if it doesn't exist.</div>
    <form method="POST">
      <input type="hidden" name="step" value="2">
      <div class="field-row">
        <div class="field">
          <label>Database Host *</label>
          <input type="text" name="db_host" value="<?= htmlspecialchars($setup['db_host'] ?? 'localhost') ?>" placeholder="localhost" required>
        </div>
        <div class="field">
          <label>Port</label>
          <input type="number" name="db_port" value="<?= htmlspecialchars($setup['db_port'] ?? '3306') ?>" placeholder="3306">
        </div>
      </div>
      <div class="field-row">
        <div class="field">
          <label>Username *</label>
          <input type="text" name="db_user" value="<?= htmlspecialchars($setup['db_user'] ?? 'root') ?>" placeholder="root" required>
        </div>
        <div class="field">
          <label>Password</label>
          <input type="password" name="db_pass" placeholder="Leave blank if none" autocomplete="new-password">
        </div>
      </div>
      <div class="field">
        <label>Database Name *</label>
        <input type="text" name="db_name" value="<?= htmlspecialchars($setup['db_name'] ?? 'projectrbi') ?>" placeholder="projectrbi" required>
        <div class="field-hint">Will be created automatically if it doesn't exist</div>
      </div>
      <div class="btn-row">
        <a href="setup.php?step=1" class="btn btn-ghost">&larr; Back</a>
        <button type="submit" class="btn btn-primary">Test &amp; Continue &rarr;</button>
      </div>
    </form>
  </div>

  <!-- ── STEP 3: Admin Account ── -->
  <?php elseif ($step === 3): ?>
  <div class="card">
    <div class="card-title"><i class="fas fa-user-shield"></i> Admin Account</div>
    <div class="card-sub">Create the first administrator account for the system.</div>
    <form method="POST">
      <input type="hidden" name="step" value="3">
      <div class="field">
        <label>Full Name *</label>
        <input type="text" name="admin_name" placeholder="e.g. Juan Dela Cruz" required>
      </div>
      <div class="field">
        <label>Username *</label>
        <input type="text" name="admin_user" placeholder="e.g. captain_juan" autocomplete="username" required>
      </div>
      <div class="field">
        <label>Role *</label>
        <select name="admin_role">
          <option value="captain">Punong Barangay (Captain)</option>
          <option value="secretary">Barangay Secretary</option>
        </select>
      </div>
      <div class="field-row">
        <div class="field">
          <label>Password * (min 8 chars)</label>
          <input type="password" name="admin_pass" id="adminPass" placeholder="Password" autocomplete="new-password" required oninput="checkStrength(this.value)">
          <div class="pw-strength" id="pwStrength"></div>
        </div>
        <div class="field">
          <label>Confirm Password *</label>
          <input type="password" name="admin_pass2" placeholder="Repeat password" required>
        </div>
      </div>
      <div class="alert alert-info" style="margin-top:.5rem">
        <i class="fas fa-info-circle" style="flex-shrink:0"></i>
        <span>You can add more accounts (secretary, kagawad) after installation from the Manage Accounts page.</span>
      </div>
      <div class="btn-row">
        <a href="setup.php?step=2" class="btn btn-ghost">&larr; Back</a>
        <button type="submit" class="btn btn-primary">Create Account &amp; Install &rarr;</button>
      </div>
    </form>
  </div>

  <!-- ── STEP 4: Installing ── -->
  <?php elseif ($step === 4): ?>
  <div class="card">
    <div class="card-title"><i class="fas fa-cog fa-spin"></i> Installing...</div>
    <div class="card-sub">Setting up your system. Please wait.</div>
    <form method="POST" id="installForm">
      <input type="hidden" name="step" value="4">
    </form>
    <script>document.getElementById('installForm').submit();</script>
  </div>

  <!-- ── STEP 5: Done ── -->
  <?php elseif ($step === 5):
    $log  = $_SESSION['install_log']  ?? [];
    $fail = $_SESSION['install_fail'] ?? false;
  ?>
  <div class="card">
    <div class="card-title">
      <?php if (!$fail): ?>
      <i class="fas fa-circle-check" style="color:#22c55e"></i> Installation Complete!
      <?php else: ?>
      <i class="fas fa-circle-xmark" style="color:#ef4444"></i> Installation Failed
      <?php endif; ?>
    </div>
    <div class="card-sub">
      <?= $fail ? 'Some steps failed. Fix the errors and try again.' : 'Your system is ready to use.' ?>
    </div>

    <!-- Log -->
    <div style="margin-bottom:1.5rem">
      <?php foreach ($log as $item): ?>
      <div class="log-item <?= $item['ok'] ? 'ok' : 'fail' ?>">
        <i class="fas <?= $item['ok'] ? 'fa-check-circle' : 'fa-times-circle' ?>"></i>
        <?= htmlspecialchars($item['msg']) ?>
      </div>
      <?php endforeach; ?>
    </div>

    <?php if (!$fail): ?>
    <div class="alert alert-warning">
      <i class="fas fa-triangle-exclamation" style="flex-shrink:0;margin-top:2px"></i>
      <div>
        <strong>Important — Delete setup.php!</strong><br>
        For security, delete this installer file from your server before going live.
        <code style="display:block;margin-top:.35rem;font-size:.8rem;opacity:.8">rm setup.php</code>
      </div>
    </div>

    <div class="alert alert-success">
      <i class="fas fa-circle-check" style="flex-shrink:0;margin-top:2px"></i>
      <div>
        <strong>Setup complete!</strong><br>
        Login with username: <strong><?= htmlspecialchars($_SESSION['setup']['admin_user'] ?? '') ?></strong>
      </div>
    </div>

    <div class="btn-row" style="justify-content:center">
      <a href="admin.php" class="btn btn-success"><i class="fas fa-right-to-bracket"></i> Go to Login</a>
      <a href="Home.php" class="btn btn-ghost"><i class="fas fa-house"></i> Go to Dashboard</a>
    </div>
    <?php else: ?>
    <div class="btn-row" style="justify-content:center">
      <a href="setup.php?force=1" class="btn btn-danger"><i class="fas fa-rotate"></i> Try Again</a>
    </div>
    <?php endif; ?>
  </div>
  <?php endif; ?>

  <div class="installer-footer">
    ProjectRBI &mdash; Barangay Records & Blotter Information System &mdash; v<?= INSTALLER_VERSION ?><br>
    &copy; <?= date('Y') ?> ProjectRBI. For barangay use only.
  </div>

</div>

<script>
function checkStrength(pw) {
  const el = document.getElementById('pwStrength');
  if (!el) return;
  if (pw.length === 0) { el.className = 'pw-strength'; return; }
  const strong = pw.length >= 12 && /[A-Z]/.test(pw) && /[0-9]/.test(pw) && /[^A-Za-z0-9]/.test(pw);
  const medium = pw.length >= 8 && (/[A-Z]/.test(pw) || /[0-9]/.test(pw));
  el.className = 'pw-strength ' + (strong ? 'strong' : medium ? 'medium' : 'weak');
}
</script>
</body>
</html>